name: Selenide Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: windows-latest
    services:
      selenium:
        image: selenium/standalone-firefox
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
        
    - name: Run Selenide tests
      run: mvn test -Dselenide.remote=http://localhost:4444/wd/hub -Dtest=Tests_TextBox
      
    - name: Create Allure directories
      run: |
        mkdir -p target/allure-results
        mkdir -p target/allure-report
    
    - name: Generate Allure Report
      if: always()
      run: |
        mvn allure:report
        echo "Allure results:"
        ls -la target/allure-results
        echo "Allure report:"
        ls -la target/site/allure-maven-plugin
    
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/site/allure-maven-plugin
